
[functions.admin-payment-notification]
enabled = true
verify_jwt = true
import_map = "./functions/admin-payment-notification/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/admin-payment-notification/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/admin-payment-notification/*.html" ]

[functions.video-stream]
verify_jwt = false

[functions.telegram-fileid-helper]
enabled = true
verify_jwt = true
import_map = "./functions/telegram-fileid-helper/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/telegram-fileid-helper/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/telegram-fileid-helper/*.html" ]
